version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: install-build-dependency
          command: 'yarn install'
      - run:
          name: build-production
          command: 'yarn build'
      - run:
          name: run-tests
          command: 'yarn test'
